language: cpp
compiler:
  - clang


before_script: chmod +x ./snap/install.py; ./snap/install.py 
script: chmod +x ./compile_and_run_test.sh; ./compile_and_run_test.sh
after_script: cat ./build/Testing/Temporary/LastTest.log

